package com.bjpowernode.crm.workbench.mapper;

import com.bjpowernode.crm.workbench.domain.Activity;
import com.bjpowernode.crm.workbench.domain.FunnelVO;
import com.bjpowernode.crm.workbench.domain.Tran;

import java.util.List;
import java.util.Map;

public interface TranMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Sun Jun 12 15:44:48 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Sun Jun 12 15:44:48 CST 2022
     */
    int insert(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Sun Jun 12 15:44:48 CST 2022
     */
    int insertSelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Sun Jun 12 15:44:48 CST 2022
     */
    Tran selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Sun Jun 12 15:44:48 CST 2022
     */
    int updateByPrimaryKeySelective(Tran record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_tran
     *
     * @mbggenerated Sun Jun 12 15:44:48 CST 2022
     */
    int updateByPrimaryKey(Tran record);

    /**
     * 保存创建的交易
     * @param tran
     * @return
     */
    int insertTran(Tran tran);

    /**
     * 根据id查询交易详情
     * @param id
     * @return
     */
    Tran selectTranForDetailById(String id);

    /**
     * 查询交易表中各个阶段的数据量
     * @return
     */
    List<FunnelVO> selectCountOfTranGroupByStage();

    /**
     * 根据条件 分页查询交易
     * @param map
     * @return
     */
    List<Tran> selectTranByConditionForPage(Map<String,Object> map);

    /**
     * 根据条件 查询交易总记录数
     * @param map
     * @return
     */
    int selectCountOfTranByCondition(Map<String,Object> map);

    /**
     * 根据数组id 删除交易
     * @param id
     * @return
     */
    int deleteTranByIds(String[] id);

    /**
     * 根据id 查询交易信息
     * @param id
     * @return
     */
    Tran selectTranById(String id);

    /**
     * 跟新交易信息
     * @param tran
     * @return
     */
    int updateTran(Tran tran);

    /**
     * 根据customerId 查询交易详情
     * @param customerId
     * @return
     */
    List<Tran> selectTranForDetailByCustomerId(String customerId);

    /**
     * 根据联系人id  查询相关绑定交易
     * @param contactsId
     * @return
     */
    List<Tran> selectTranForDetailByContactsId(String contactsId);

    /**
     * 根据联系人id查询对应的交易数量
     * @return
     */
    List<FunnelVO> selectCountOfTranByContactsId();

    /**
     * 根据客户id查询对应的交易数量
     * @return
     */
    List<FunnelVO> selectCountOfTranByCustomerId();

    List<Tran> selectSuccessfulTranByStage();
}